# Generated by Django 4.1.13 on 2024-09-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Category Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Item Slug')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('recordedAt', models.DateTimeField(auto_now_add=True, verbose_name='recordedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_supplied', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='SubCategory Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='SubCategory Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_in_stock', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory', verbose_name='sub_category'),
        ),
    ]
